
<div class="block block-layered-nav">
	<div class="block-title">
		<strong><span><?php echo $this->__('Narrow Search By') ?></span></strong>
	</div>
	<div class="block-content">
		<!-- TODO Add block to list selected filters -->
		<dl id="narrow-by-list">
			<?php $facets = $this->getFacets() ?>
			<?php foreach ($facets as $facet): ?>
			<?php if (count($facet->getOptions())): ?>
				<dt>
					<?php echo $facet->getLabel() ?>
					<!-- TODO move the following ul into a separate block -->
					<dd>
						<ol>
						<?php foreach ($facet->getOptions() as $facetOption): ?>
							<li>
								<?php echo $facetOption->getLabel() ?>
								<?php if ($this->shouldDisplayProductCount()): ?>
									(<?php echo $facetOption->getNumberOfResults() ?>)
								<?php endif; ?>
							</li>
						<?php endforeach ?>
						</ol>
					</dd>
				</dt>
			<?php endif ?>
			<?php endforeach ?>
		</dl>
	</div>
</div>
