<?php
/* @var $this Asm_Solr_Block_Form_Mini */
/* @var $solrHelper Asm_Solr_Helper_Data */
$solrHelper = $this->helper('solr');
?>
<form id="search_mini_form"
	  action="<?php echo $solrHelper->getResultUrl() ?>"
	  method="get">
	<div class="form-search">
		<label for="search"><?php echo $this->__('Search:') ?></label>
		<input id="search" type="text"
			   name="<?php echo $solrHelper->getQuery()->getQueryParameterName() ?>"
			   value="<?php echo $solrHelper->getQuery()->getKeywordsCleaned() ?>"
			   class="input-text" />
		<button type="submit" title="<?php echo $this->__('Search') ?>" class="button">
			<span><span><?php echo $this->__('Search') ?></span></span>
		</button>
	</div>
</form>
